import type { Metadata } from 'next';
import Link from 'next/link';
import { Nav } from '@/components/landing/Nav';
import { Footer } from '@/components/landing/Footer';
import '../../(home)/landing.css';
import '../trust.css';

export const metadata: Metadata = {
  title: 'Data Processing Agreement',
  description:
    'Data Processing Agreement template for VectorFlow Cloud customers. Signed copy available on request.',
};

export default function DpaPage() {
  return (
    <>
      <Nav />
      <main className="trust">
        <header className="trust-hero wrap">
          <h1>Data Processing Agreement</h1>
          <p className="lede">
            This page is a public summary of VectorFlow Cloud&rsquo;s DPA so
            you can read the substance before requesting a signable copy.
            Email{' '}
            <a href="mailto:trust@vectorflow.sh" className="link">
              trust@vectorflow.sh
            </a>{' '}
            with your legal entity name and we will return a counter-signable
            PDF within two business days.
          </p>
          <p className="trust-meta">
            Template version: 1.1 (2026-05-17 — §15a R5 stale-link fix; security-measures section now references the internal threat model via the NDA path).
          </p>
        </header>

        <section className="wrap trust-section">
          <h2>1. Roles</h2>
          <p>
            <strong>Customer</strong> is the data controller for any personal
            data submitted to or generated by the VectorFlow Cloud service.
            <strong> VectorFlow</strong> is the data processor and processes
            personal data only on the documented instructions of Customer
            (including the terms of this DPA).
          </p>
        </section>

        <section className="wrap trust-section">
          <h2>2. Categories of data processed</h2>
          <ul className="trust-list">
            <li>
              <strong>Account &amp; identity data:</strong> email addresses,
              names, organization name, role assignments.
            </li>
            <li>
              <strong>Configuration data:</strong> pipeline definitions, alert
              rules, notification channel destinations.
            </li>
            <li>
              <strong>Operational metadata:</strong> fleet node hostnames,
              heartbeat state, version drift, deploy history.
            </li>
            <li>
              <strong>Bounded telemetry:</strong> metric rollups and capped
              event samples retained per the schedule in{' '}
              <Link href="/trust" className="link">
                Trust &amp; Security
              </Link>
              .
            </li>
          </ul>
          <p className="muted">
            VectorFlow does <strong>not</strong> process raw log data: it
            remains within the customer&rsquo;s network.
          </p>
        </section>

        <section className="wrap trust-section">
          <h2>3. Sub-processors</h2>
          <p>
            VectorFlow uses the sub-processors listed at{' '}
            <Link href="/trust/subprocessors" className="link">
              /trust/subprocessors
            </Link>
            . Customer is provided 30 days&rsquo; advance notice of any new
            sub-processor and may object in writing; if the objection cannot be
            resolved Customer may terminate the affected service component with
            pro-rata refund of pre-paid fees.
          </p>
        </section>

        <section className="wrap trust-section">
          <h2>4. Security measures</h2>
          <p>
            VectorFlow implements the technical and organizational measures
            summarised on the{' '}
            <Link href="/trust" className="link">
              Trust &amp; Security overview
            </Link>
            . The full Cloud threat model is internal; customers under NDA
            can request a redacted review copy from{' '}
            <a href="mailto:trust@vectorflow.sh" className="link">
              trust@vectorflow.sh
            </a>
            . Measures include:
          </p>
          <ul className="trust-list">
            <li>
              Per-organization data encryption keys wrapped with AWS KMS;
              AES-256-GCM with AAD binding ciphertexts to their owning org.
            </li>
            <li>
              Postgres Row-Level Security with the application running under a
              <code> NOBYPASSRLS</code> role.
            </li>
            <li>
              Break-glass operator decrypt workflow with customer-admin email
              notification and two independent audit logs.
            </li>
            <li>
              Hash-chained customer audit log with externally verifiable export.
            </li>
            <li>
              Outbound URL validation against private/link-local/metadata IP
              ranges (IPv4 + IPv6).
            </li>
            <li>
              At-rest encryption on the database and S3 buckets backing the
              service.
            </li>
          </ul>
        </section>

        <section className="wrap trust-section">
          <h2>5. International transfers</h2>
          <p>
            Where data transfers occur outside the European Economic Area or
            the United Kingdom, VectorFlow relies on Standard Contractual
            Clauses (SCCs) and where applicable the UK International Data
            Transfer Addendum. By default Customer data is processed in the EU
            (AWS <code>eu-west-2</code>); US processing requires explicit
            Customer opt-in at signup.
          </p>
        </section>

        <section className="wrap trust-section">
          <h2>6. Data subject requests</h2>
          <p>
            VectorFlow assists Customer in responding to data subject requests
            (access, rectification, erasure, portability) within 30 days. The
            customer-side audit export and organization export endpoints fulfil
            the data-portability obligation programmatically (GDPR Art. 20).
            Erasure is performed by deleting the organization, which triggers a
            90-day cool-off followed by crypto-shredding the per-org DEK; once
            the DEK is destroyed the ciphertext is computationally inert.
          </p>
        </section>

        <section className="wrap trust-section">
          <h2>7. Personal data breach notification</h2>
          <p>
            VectorFlow notifies Customer of a personal data breach affecting
            Customer&rsquo;s data without undue delay and in any event within
            72 hours of confirmation. The notification includes the nature of
            the breach, categories and approximate number of data subjects
            affected, likely consequences, and the measures taken or proposed
            to be taken to mitigate.
          </p>
        </section>

        <section className="wrap trust-section">
          <h2>8. Audit rights</h2>
          <p>
            Customer may audit VectorFlow&rsquo;s compliance with this DPA once
            per year on 30 days&rsquo; written notice. VectorFlow will provide
            the most recent SOC 2 Type II report (when available) and may
            request that the audit be carried out by a mutually agreed
            independent third party. Customer bears the cost of any audit it
            initiates.
          </p>
        </section>

        <section className="wrap trust-section">
          <h2>9. Term &amp; return / deletion of data</h2>
          <p>
            On termination Customer may export their data via the Article 20
            endpoints during a 30-day grace period. After the grace period
            VectorFlow deletes all Customer personal data in active systems
            within 30 days; backups containing Customer data are retained no
            longer than 90 days and are not restored except for disaster
            recovery.
          </p>
        </section>

        <section className="wrap trust-section">
          <p>
            Questions: <a href="mailto:trust@vectorflow.sh" className="link">
              trust@vectorflow.sh
            </a>. Return to{' '}
            <Link href="/trust" className="link">
              Trust &amp; Security overview
            </Link>
            .
          </p>
        </section>
      </main>
      <Footer />
    </>
  );
}
